server:
  port: 8088

spring:
  application:
    name: ms-inventory
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    baselineOnMigrate: true
    schemas: ${spring.jpa.properties.hibernate.default_schema:inventory}
    enabled: true
    locations: "classpath:db/migration/"
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: inventory